services:
  mysql:
    image: mysql:8
    container_name: mysql_dev
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: pw_mysql
      TZ: Asiz/Shanghai
    ports:
      - '13306:3306'
    volumes:
      - '/Users/jayhoo/Documents/workspace/envs/mysql2/data:/var/lib/mysql'
      - '/Users/jayhoo/Documents/workspace/envs/mysql2/logs:/var/log/mysql'
    command: ['--character-set-server', 'utf8mb4', '--collation-server', 'utf8mb4_general_ci']
    networks:
      - db-net

networks:
  db-net:
    driver: bridge
    name: db-net